---
title: "Research"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Publications

1. **A. ElHabr**, S. Merdan, R. Duscak, M. Horn&#253;, T. Hanna, A. Prater, T. Ayer, D. Hughes (2022). Increasing Utilization of Emergency Department Neuroimaging From 2007 Through 2017. *American Journal of Roentgenology*, 218(1), 165-173. [paper](https://www.ajronline.org/doi/abs/10.2214/AJR.21.25864)
2. **A. ElHabr**, J. Katz, J. Wang, M. Bastani, G. Martinez, M. Gribko, D. Hughes, P. Sanelli (2021). Predicting 90-Day Modified Rankin Scale Score with Discharge Information in Acute Ischaemic Stroke Patients Following Treatment. *BMJ Neurology Open*, 3(1). [paper](https://neurologyopen.bmj.com/content/3/1/e000177)

### Working Papers

1. **A. ElHabr**, T. Ayer, C. Zhang (2022). Outcome-based Pharmaceutical Contracting with Heterogenous Patient Groups.
2. **A. ElHabr**, T. Ayer, J. Newsome, N. Kokabi, R. Smith,  J. Gichoya (2022). Racial Disparities in Utilization of Interventional Radiology, Operative, and Non-operative Hemorrhage Management for Patients with Traumatic Injuries: A National Trauma Data Bank Study.
3. **A. ElHabr**, T. Ayer, J. Katz, J. Wang, M. Bastani, M. Gribko, D. Hughes, P. Sanelli (2022). Development and Validation of an Administrative Claims Stroke Severity Score via Ensembling Across Multiple Databases.
4. N. Shiban, J. Gaul, H. Zhang, **A. ElHabr**, N. Kokabi, J. Johnson, T. Hanna, J. Schrager, J. Gichoya, I. Banarjee, H. Trivedi (2021). Machine Learning Methods to Predict Survival in Patients Following Traumatic Aortic Injury. *medRxiv*. [paper](https://www.medrxiv.org/content/10.1101/2021.07.28.21261166v1)

### Presentations

- Outcome-based Pharmaceutical Contracting for Heterogeneous Patient Groups (*POMS 2019, INFORMS Annual Meeting 2019, INFORMS Annual Meeting 2021*)
- Value of Diagnostic Imaging Prior to Embolization in Pelvic-related Trauma Patients (*INFORMS Healthcare 2021*)

